# ????
spring.application.name=e_sum_social_media_platform

# ??????? (????????? esun_social_db)
spring.datasource.url=jdbc:postgresql://localhost:5432/esun_social_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate ??
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?? Open In View ?? (??)
spring.jpa.open-in-view=false